### ISSUE TITLE
No device gets added

### ISSUE THREAD

**Issue by Tim-Brass** [athombv/nl.philips.ir#1]
After selecting the correct remote nothing gets added to the devices.

![image](https://user-images.githubusercontent.com/19285656/28779881-0cf798f4-7605-11e7-8cb0-c4f14b2733d0.png)

**Comment by caseda** [comment]
fixed in the last update (1.0.3)

**Comment by BasKiers** [comment]
Hi,

Sorry there was a bug in the app for Homey versions lower than 1.5. This should be fixed like caseda mentioned. Thanks for the bug report!

Regards,
Bas
