### ISSUE TITLE
Setting to channels above 9 (10 and up) not working

### ISSUE THREAD

**Issue by kukel** [athombv/nl.philips.ir#3]
Using Homey 1.5.0-rc2 and Philips TV IR 1.0.2, setting the channel to anything other than 1-9 fails when used in a flow. When setting the channel to e.g. 1234, it sometimes sets the channel mostly to a random combination of two non-adjacent numbers out of this string, 13, 24 and 14 (12, 23 and 34 happening way less)

Also using send command feature and sending a '2' and 1 second later a '0' does not set the channel to '20' (in fact does not do anything). Not sure if this is related in a way or not, just thought I'd mention it

**Comment by BasKiers** [comment]
Hi Kukel,

Both issues are indeed related since the flow card: set the channel to 20 is executed as the command '2' followed by the command '0' 250ms later. Could you check what behaviour your tv is expecting by setting the channel to 20 using your tv remote?

Regards,
Bas

**Comment by kukel** [comment]
it is expecting 2...0 and if I do that with my normal remote e.g. with channel 222 (quickly pressing the 2 three times, If I do it too quick, it fails to and has the same behaviour as doing it from Homey. If I implement a flow where I send command 2, another one with a delay of 1s, and a third one with a delay of 2s, it works (most of the time, sometimes it fails). Seems like the delay of 250ms is to little and the 1s delay in flows (less cannot be configured) is at the top end... So maybe 250ms should become 300, or 350...

**Comment by BasKiers** [comment]
Hi,

I can change this value. Could you tell me which driver has this problem? is it the driver for old or new models?

Regards,
Bas

**Comment by kukel** [comment]
New Driver... Normally I'd try this myself from source but I unfortunately don't have the time due to investigating to start my own business.

**Comment by kukel** [comment]
Feedback:  With the latest 1.1.0 driver, When I try setting it to channel 310, it ends up at 3131... Not a real improvement (and the new app already crashed 3 times in 5 minutes after using it)

**Comment by kukel** [comment]
Any progress???

**Comment by open-gdsn** [comment]
Any progress??? Seriously...

**Comment by kukel** [comment]
Any progress??? Seriously

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2604
