### ISSUE TITLE
"zet de tv op kanaal 22" geeft "ik kon geen tv vinden om het volume van aan te passen naar een specfieke waarde"

### ISSUE THREAD

**Issue by kukel** [athombv/nl.philips.ir#4]
Homey 1.5.0-RC2, Philips IR 1.0.2 on a new model tv.

 Same is true for the English "set the tv to channel 22". Cannot find in the documentation anywhere which sentence should be used. I do not seem to be able to find anything in the source of this philips ir app, nor in the homey core where this might be handled... So I cannot provide more info at the moment (might even be that this is all still under development since there seems to be a lot of unrelated js in the source of this app.

**Comment by bvdbos** [comment]
TV is a class in Homey, Homey has no way of knowing how the IR signal is connected to a TV. What you could do is create a virtual device with class tv and cretae a flow to act on that. So if "virtual tv clicked off" then send IR-signal off...

**Comment by kukel** [comment]
@bvdbos: Sorry but I think you either posted this answer on the wrong issue (there is one about on/off, but this answer is not even really related to that one either) or you totally misunderstood the question.

**Comment by kukel** [comment]
@bvdbos: this topic https://forum.athom.com/discussion/3321/tv-aanzetten-met-spraak#latest has no relation to mine... If the TV is off, I have no problem turning it on (but turning it OFF is my other issue  with the Philips IR but that to has no relation to the topic you posted to)

**Comment by BasKiers** [comment]
Hi Kukel,

The issue you are experiencing is caused by Homey parsing your query to "set tv volume to 22%" since setting the channel is not implemented. I will look into implementing this speech command in the ir apps.

Regards,
Bas

**Comment by kukel** [comment]
Great thanks... Can you tell me where the sourcecode is in github that enventually processes the "set tv volume to 22%)? Which app handles it? (just curious to learn the inner workings of Homey more)

**Comment by kukel** [comment]
@BasKiers: Any info on this?

**Comment by kukel** [comment]
Any progress on this?

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2603
