### ISSUE TITLE
"Zet alles in de woonkamer uit" does not switch of the TV

### ISSUE THREAD

**Issue by kukel** [athombv/nl.philips.ir#5]
It's a default/built-in flow, not one created by me.

"Zet de TV uit" does not switch it of. 

"Zet alles in de woonkamer aan" schakelt de TV wel aan! 

Is one of these lines related? 

  - https://github.com/athombv/nl.philips.ir/blob/master/ir_generator/config.js#L206
  - https://github.com/athombv/nl.philips.ir/blob/master/drivers/new_tv/driver.js#L44

The code there is 

    capabilityToCommandMap: {
        onoff: ['power_on', 'onoff'],

Since for the samsung TV I noticed:

https://github.com/athombv/com.samsung.ir/blob/master/drivers/remote/driver.js#L20

    capabilityToCommandMap: {
        onoff: ['power_on', 'power_off'],

Which sounds more logical.

Home 1.5.0-RC2, Philips IR 1.0.2

**Comment by kukel** [comment]
This also happens on Homey 1.5.2, so it is not Homey related. What also happens is that if the tv is off  and you switch everything off in the living room, the tv is actually switched on...

**Comment by kukel** [comment]
And if you turned it on via Homey, it **is** turned of, so the code issue I found really seems the cause.

**Comment by BasKiers** [comment]
Hi,

This is intentional since we do not have the prontohex code for power_off for philips tv's. I will try to search for the prontohex code but for now this is intended behaviour.

Regards,
Bas

**Comment by kukel** [comment]
Ok, but keep in mind that turning the TV on or off is one of the more common usecase in flows. You'd then have to built another flow that detects if the tv was turned on with the normal remote which might not be possible since if I remember correctly it is not IR)

**Comment by kukel** [comment]
RC6 - 000,061 - System standby / Power off
RC5 - 0,61 - System standby / Power off

See 

  - https://toengel.net/philipsblog/2012/02/07/philips-alle-diskreten-ir-codes-fr-2010er-tv-gerte/
and
  - http://www.supportforum.philips.com/en/showthread.php?1563-58PFL9955H-Discrete-IR-Remote-Codes&p=7254&viewfull=1#post7254

Any chance a 1.1.2-Beta can be released with this added (then I'll check the other fix you made to)

**Comment by kukel** [comment]
@BasKiers: Any progress on this?

**Comment by kukel** [comment]
Any Progress? There has been a 1.2 release

**Comment by kukel** [comment]
Any progress or AT LEAST feedback? There has been a 2.0 and 2.0.1 release...

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2602
