### ISSUE TITLE
Suggestion: Add Philips HiFi

### ISSUE THREAD

**Issue by zperx** [athombv/nl.philips.ir#6]
Could you please add a remote for a Philips HiFi to make this app complete? Nowadays not many are using the TV speakers, TVs are just too thin to accommodate proper audio system.

**Comment by 4tetra4** [comment]
That would be awesome. Very much needed addition.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2601
